# TASK-1

1. Write a function to compute 5/0 and use try/except to catch the exception.

In [1]:
# divide function definition using exception handling concept
def divide(x, y):
    try:
        result = int(x)/int(y)
    except ZeroDivisionError:
        print("Error:division by zero!")
    else:
        print("result is", result)
# Taking two input from user
n1 = input("Enter the num1:")
n2 = input("Enter the num2:")
# Calling "divide"  function
divide(n1,n2)

Enter the num1:5
Enter the num2:0
Error:division by zero!


2. Implement a python program to generate all sentence where subject is in ["Americans",Indians"] and verb is in ["play","watch"] and the object is in  ["Baseball", "Cricket"]. 

In [3]:
#List Definition
subjects = ["Americans","Indians"]
verbs = ["play","watch"]
objects = ["Baseball","Cricket"]
#Iteration over each list
for subject in subjects:
    for verb in verbs:
        for object in objects:
            # printing each element of list in specified format
            print(subject+" "+verb+" "+object+".")

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# TASK-2

1. Write a function so that the columns of the output matrix are the power of the input vector.
    The order of the power is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wiseto the power of (N-i-1).

In [4]:
import numpy as np
def ATVanderMonde(x,n=0):
    if n is 0:
        n = len(x)
    List1 = []
    for data in x:
        for i in range(n):
            List1.append(data**(n-1-i))
    matrix = np.array(List1).reshape((len(x),n))
    return matrix

List = [1,2,3,4,5]
mat = ATVanderMonde(List,3)
#print(type(mat))
print(mat)

<class 'numpy.ndarray'>
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
